[package]
name = "hamtransfer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raptor-code = "1.0.5"

[[bin]]
name = "uploader"
path = "src/uploader/main.rs"

[[bin]]
name = "downloader"
path = "src/downloader/main.rs"
